/* auto-generated by NAPI-RS */
/* eslint-disable */

import type { Buffer } from 'node:buffer'

export type DicomInput =
  | { path: string }
  | { bytes: Uint8Array; filename?: string }

export type VolumeHandler =
  | 'keep'
  | 'central-slice'
  | { kind: 'max-intensity'; skipStart?: number; skipEnd?: number }
  | { kind: 'interpolate'; targetFrames: number }
  | { kind: 'laplacian-mip'; skipStart?: number; skipEnd?: number }

export interface PrepareOptions {
  volumeHandler?: VolumeHandler
  /** Reverse the display x axis. Raw `renderFrame` output is unchanged. */
  flipHorizontal?: boolean
  /** Reverse the display y axis. Raw `renderFrame` output is unchanged. */
  flipVertical?: boolean
}

export type FrameSource =
  | { kind: 'stored'; storedFrameIndex: number }
  | { kind: 'derived' }

export interface FramePlan {
  displayFrames: FrameSource[]
  storedFrameOrder: number[]
  frameOrderStrategy: string
  zSpacingMm?: number
}

/** Canvas-style affine matrix `[a, b, c, d, e, f]`. */
export type AffineMatrix2D = [number, number, number, number, number, number]

export interface PixelDimensions {
  width: number
  height: number
}

/** Half-open rectangle in pixel-edge coordinates. */
export interface PixelRect {
  left: number
  top: number
  width: number
  height: number
}

/**
 * Maps between source-DICOM and rendered pixel coordinates.
 * Integer coordinates identify pixel centers.
 */
export interface CoordinateTransform {
  sourceDimensions: PixelDimensions
  displayDimensions: PixelDimensions
  sourceToDisplay: AffineMatrix2D
  displayToSource: AffineMatrix2D
  validSourceRect: PixelRect
  validDisplayRect: PixelRect
}

export interface FrameMetadata {
  width: number
  height: number
  dtype: 'uint8' | 'int8' | 'uint16' | 'int16'
  samplesPerPixel: number
  photometricInterpretation: string
  pixelSpacing?: [number, number]
  rescaleSlope: number
  rescaleIntercept: number
  windowCenter?: number
  windowWidth?: number
}

export interface RenderedFrame extends FrameMetadata {
  displayFrameIndex: number
  source: FrameSource
  coordinateTransform: CoordinateTransform
  data: Buffer
}

export interface VerificationTagPath {
  group: number
  element: number
  item?: number | null
}
export interface VerificationTagExpectation {
  path: VerificationTagPath[]
  vr: string
  values: string[]
}
export interface VerificationFrameExpectation {
  width: number
  height: number
  samplesPerPixel: 1 | 3
  planarConfiguration: 0 | 1
  sampleType: 'u8' | 'i8' | 'u16' | 'i16'
  values: number[]
  absoluteTolerance?: number
}
export interface VerificationCase {
  id: string
  dicomBytes: Uint8Array
  transferSyntaxUid: string
  tags: VerificationTagExpectation[]
  frames: VerificationFrameExpectation[]
}
export interface VerificationCodec {
  id: string
  requiredCases: Record<string, string[]>
}
export interface VerificationCheck {
  name: string
  passed: boolean
  diagnostic?: string | null
}
export interface VerificationCustomTest {
  id: string
  run: () => VerificationCheck[]
}
export interface VerificationOptions {
  cases?: VerificationCase[]
  codecs?: VerificationCodec[]
  tests?: VerificationCustomTest[]
}
export interface VerificationCaseResult {
  id: string
  source: 'embedded_fixture' | 'generated_fixture' | 'extension_fixture' | 'custom'
  path: 'shared_library' | 'caller_integration'
  transferSyntaxUid: string | null
  passed: boolean
  checks: VerificationCheck[]
}
export interface VerificationCodecResult {
  id: string
  transferSyntaxUid: string
  requiredCases: string[]
  sharedLibraryVerified: boolean
  passed: boolean
}
export interface VerificationReport {
  schemaVersion: number
  suiteVersion: string
  libraryVersion: string
  passed: boolean
  cases: VerificationCaseResult[]
  codecs: VerificationCodecResult[]
}
export declare class PreparedDicom {
  get framePlan(): FramePlan
  renderFrame(frameIndex: number): RenderedFrame
  renderDisplayFrame(frameIndex: number): RenderedFrame
}

export interface NodeCoordinateTransform {
  sourceDimensions: NodePixelDimensions
  displayDimensions: NodePixelDimensions
  sourceToDisplay: [number, number, number, number, number, number]
  displayToSource: [number, number, number, number, number, number]
  validSourceRect: NodePixelRect
  validDisplayRect: NodePixelRect
}

export interface NodeFramePlan {
  displayFrames: Array<NodeFrameSource>
  storedFrameOrder: Array<number>
  frameOrderStrategy: string
  zSpacingMm?: number
}

export interface NodeFrameSource {
  kind: string
  storedFrameIndex?: number
}

export interface NodePixelDimensions {
  width: number
  height: number
}

export interface NodePixelRect {
  left: number
  top: number
  width: number
  height: number
}

export interface NodeRenderedFrame {
  displayFrameIndex: number
  source: NodeFrameSource
  coordinateTransform: NodeCoordinateTransform
  data: Buffer
  width: number
  height: number
  dtype: string
  samplesPerPixel: number
  photometricInterpretation: string
  pixelSpacing?: [number, number] | undefined
  rescaleSlope: number
  rescaleIntercept: number
  windowCenter?: number
  windowWidth?: number
}

export declare function prepareDicom(input: DicomInput, options?: PrepareOptions): PreparedDicom

export declare function renderDisplayFrame(prepared: PreparedDicom, frameIndex: number): RenderedFrame

export declare function renderFrame(prepared: PreparedDicom, frameIndex: number): RenderedFrame

export declare function verifyRuntime(options?: VerificationOptions): VerificationReport
