/* auto-generated by NAPI-RS */
/* eslint-disable */

import type { Buffer } from 'node:buffer'

export type DicomInput =
  | { path: string }
  | { bytes: Uint8Array; filename?: string }

export type VolumeHandler =
  | 'keep'
  | 'central-slice'
  | { kind: 'max-intensity'; skipStart?: number; skipEnd?: number }
  | { kind: 'interpolate'; targetFrames: number }
  | { kind: 'laplacian-mip'; skipStart?: number; skipEnd?: number }

export interface PrepareOptions {
  volumeHandler?: VolumeHandler
}

export type FrameSource =
  | { kind: 'stored'; storedFrameIndex: number }
  | { kind: 'derived' }

export interface FramePlan {
  displayFrames: FrameSource[]
  storedFrameOrder: number[]
  frameOrderStrategy: string
  zSpacingMm?: number
}

export interface FrameMetadata {
  width: number
  height: number
  dtype: 'uint8' | 'int8' | 'uint16' | 'int16'
  samplesPerPixel: number
  photometricInterpretation: string
  pixelSpacing?: [number, number]
  rescaleSlope: number
  rescaleIntercept: number
  windowCenter?: number
  windowWidth?: number
}

export interface RenderedFrame extends FrameMetadata {
  displayFrameIndex: number
  source: FrameSource
  data: Buffer
}
